on:
  pull_request:
    paths: ['**.go', 'go.mod', '.github/workflows/*']
  push:
    branches: ['main', 'aix']

jobs:
  # OpenBSD; no -race as the VM doesn't include the comp set.
  #
  # TODO: should probably add this, but on my local machine the tests time out
  #       with -race as the waits aren't long enough (OpenBSD is kind of slow),
  #       so should probably look into that first. Go 1.19 is supposed to have a
  #       much faster race detector, so maybe waiting until we have that is
  #       enough.
  testOpenBSD:
    runs-on: macos-12
    name: test (openbsd, 1.17)
    steps:
      - uses: actions/checkout@v3
      - name: test (openbsd, 1.17)
        id: test
        uses: vmactions/openbsd-vm@v0
        with:
          prepare: pkg_add -vvvvv go
          run: |
            useradd -mG wheel action
            su action -c 'go test ./...'

  # NetBSD
  testNetBSD:
    runs-on: macos-12
    name: test (netbsd, 1.18)
    steps:
      - uses: actions/checkout@v3
      - name: test (netbsd, 1.18)
        id: test
        uses: vmactions/netbsd-vm@v0
        with:
          prepare: pkg_add go
          # TODO: no -race for the same reason as OpenBSD (the timing; it does run).
          run: |
            useradd -mG wheel action
            su action -c 'go118 test ./...'

  # illumos
    testillumos:
      runs-on: macos-12
      name: test (illumos, 1.19)
      steps:
      - uses: actions/checkout@v2
      - name: test (illumos, 1.19)
        id: test
        uses: papertigers/illumos-vm@r38
        with:
          prepare: |
            pkg install go-119
          run: |
            useradd action
            export GOCACHE=/tmp/go-cache
            export GOPATH=/tmp/go-path
            su action -c '/opt/ooce/go-1.19/bin/go test ./...'

